services:
  paperless-ngx-metadata-exporter:
    build: .
    container_name: paperless-ngx-metadata-exporter
    restart: unless-stopped
    ports:
      - "5052:5001"
    env_file:
      - .env
    volumes:
      - paperless_ngx_metadata_exporter_data:/data

volumes:
  paperless_ngx_metadata_exporter_data:
